[default]
extend-ignore-re = [
  # Hex color codes in SCSS/CSS
  "F[0-9A-F]{2,4}",
]

[default.extend-words]
# Company/Publisher names
Packt = "Packt"
SkippBox = "SkippBox"
Skipp = "Skipp"
KOMMA = "KOMMA"
Hashi = "Hashi"  # HashiCorp

# Icon/variable names
stange = "stange"
mutliple = "mutliple"  # May be intentional in legacy code
multiplebgs = "multiplebgs"
psuedo = "psuedo"  # Legacy typo in vendor code

# Technical terms
AKS = "AKS"  # Azure Kubernetes Service
ba = "ba"
ede = "ede"  # Git commit hash

# German words in translations
Paket = "Paket"  # German for "package"

[files]
extend-exclude = [
  # Internationalization files (Docusaurus i18n directory)
  "i18n/",
  # Go dependencies
  "sdkexamples/go.mod",
  "sdkexamples/go.sum",
  # v4 changelog (don't want to change commit messages)
  "docs/changelog.md",
  # v2 docs
  "versioned_docs/version-2/*",
  # Ignore typos on files imported from remote repos (fix upstream instead)
  # See docusaurus.config.js customFields.communityDocs.remoteDocs[] for full list
  "community/art/",
  "community/hips/",
  "community/meeting-notes/",
]
