baseurl = "https://helm.sh/"
languageCode = "en-us"
theme = "helm"

contentDir = "content"
publishdir = "app"
enableEmoji = true

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
disableKinds = ["taxonomy", "taxonomyTerm"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
[markup.highlight]
style = "manni"
guessSyntax = true

[Permalinks]
code = "/:filename/"

[params]
title = "Helm"
description = "Helm - The Kubernetes Package Manager."
googleAnalyticsId = "UA-42867143-2"
googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
twittersite = "helmpack"
twittertype = "summary"
twitterimage = "img/og-image.png"
jsFiles = [
  "foundation",
  "foundation.accordion",
  "foundation.dropdown",
  "foundation.offcanvas",
  "foundation.slider",
  "foundation.tooltip",
  "modernizr",
  "clipboard.min",
  "app"
]

[[params.versions]]
version = "v3.16.0"
patch = "stable"
url = "https://helm.sh/docs"
primary = true

[[params.versions]]
version = "v2.17.0"
url = "https://v2.helm.sh/docs"

[params.nextversion]
version = "v3.17.0"
date = "January 15, 2025"

[[params.quicklinks]]
title = "Quickstart Guide"
description = "How to install and get started with Helm including instructions for distros, FAQs, and plugins."
url = "/docs/intro/quickstart"

[[params.quicklinks]]
title = "Chart Guide"
description = "Practical steps for building Helm charts—how to structure, sign, and sync your charts."
url = "/docs/topics/charts"

[[params.quicklinks]]
title = "Video: Intro to Helm"
description = "Watch Matt Farina and Josh Dolitsky present an introduction to Helm at KubeCon 2019."
url = "https://www.youtube.com/watch?v=Zzwq9FmZdsU"

[[params.quicklinks]]
title = "Migrating from v2 to v3"
description = "Read our blog post on how to migrate from Helm v2 to Helm v3."
url = "/blog/migrate-from-helm-v2-to-helm-v3/"

[[params.quicklinks]]
title = "Helm Security Audit"
description = "Helm has been audited and deemed as recommended for public deployment  during a third-party security audit funded by the CNCF."
url = "/blog/2019-11-04-helm-security-audit-results/"

# Multilingual configuration
defaultContentLanguage = "en"
disableLanguages = ["zh"]

# English
[languages.en]
title = "Helm"
description = "Helm - The Kubernetes Package Manager."
contentDir = "content/en"
languageName = "English"
weight = 1

[[languages.en.menus.main]]
name = "Home"
url = "/"
weight = 1

[[languages.en.menus.main]]
name = "Docs"
url = "/docs"
weight = 2

[[languages.en.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.en.menus.main]]
name = "Blog"
url = "/blog"
weight = 4

[[languages.en.menus.main]]
name = "Community"
url = "https://github.com/helm/community"
weight = 5

# German
[languages.de]
title = "Helm"
description = "Helm - Der Kubernetes Paket Manager."
contentDir = "content/de"
languageName = "Deutsch"
weight = 2

[[languages.de.menus.main]]
name = "Start"
url = "/"
weight = 1

[[languages.de.menus.main]]
name = "Dokumentation"
url = "/docs"
weight = 2

[[languages.de.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.de.menus.main]]
name = "Blog"
url = "https://helm.sh/blog"
weight = 4

[[languages.de.menus.main]]
name = "Gemeinschaft"
url = "https://github.com/helm/community"
weight = 5

[languages.de.params]
language_alternatives = ["en"]

# Spanish
[languages.es]
title = "Helm"
description = "Helm - El Administrador de Paquetes de Kubernetes."
contentDir = "content/es"
languageName = "Español"
weight = 3

[[languages.es.menus.main]]
name = "Inicio"
url = "/"
weight = 1

[[languages.es.menus.main]]
name = "Docs"
url = "/docs"
weight = 2

[[languages.es.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.es.menus.main]]
name = "Blog"
url = "https://helm.sh/blog"
weight = 4

[[languages.es.menus.main]]
name = "Comunidad"
url = "https://github.com/helm/community"
weight = 5

# French
[languages.fr]
title = "Helm"
description = "Helm - Le manageur de paquets de Kubernetes."
contentDir = "content/fr"
languageName = "Français"
weight = 4

[[languages.fr.menus.main]]
name = "Accueil"
url = "/"
weight = 1

[[languages.fr.menus.main]]
name = "Docs"
url = "/docs"
weight = 2

[[languages.fr.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.fr.menus.main]]
name = "Blog"
url = "https://helm.sh/blog"
weight = 4

[[languages.fr.menus.main]]
name = "Communauté"
url = "https://github.com/helm/community"
weight = 5

# Ελληνικά
[languages.gr]
title = "Helm"
description = "Helm - Ο package manager του Kubernetes."
contentDir = "content/gr"
languageName = "Ελληνικά"
weight = 5

[[languages.gr.menus.main]]
name = "Αρχική"
url = "/"
weight = 1

[[languages.gr.menus.main]]
name = "Έγγραφα"
url = "/docs"
weight = 2

[[languages.gr.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.gr.menus.main]]
name = "Άρθρα"
url = "https://helm.sh/blog"
weight = 4

[[languages.gr.menus.main]]
name = "Επικοινωνία"
url = "https://github.com/helm/community"
weight = 5

# Japanese
[languages.ja]
title = "Helm"
description = "Helm - Kubernetes パッケージマネージャー"
contentDir = "content/ja"
languageName = "日本語"
weight = 6

[[languages.ja.menus.main]]
name = "ホーム"
url = "/"
weight = 1

[[languages.ja.menus.main]]
name = "ドキュメント"
url = "/docs"
weight = 2

[[languages.ja.menus.main]]
name = "チャート"
url = "https://artifacthub.io/"
weight = 3

[[languages.ja.menus.main]]
name = "ブログ"
url = "https://helm.sh/blog"
weight = 4

[[languages.ja.menus.main]]
name = "コミュニティ"
url = "https://github.com/helm/community"
weight = 5

[languages.ja.params]
language_alternatives = ["en"]


# Korean
[languages.ko]
title = "헬름"
description = "헬름 - 쿠버네티스 패키지 매니저"
contentDir = "content/ko"
languageName = "한국어"
weight = 7

[[languages.ko.menus.main]]
name = "홈"
url = "/"
weight = 1

[[languages.ko.menus.main]]
name = "문서"
url = "/docs"
weight = 2

[[languages.ko.menus.main]]
name = "차트"
url = "https://artifacthub.io/"
weight = 3
external = "yes"

[[languages.ko.menus.main]]
name = "블로그"
url = "https://helm.sh/blog"
weight = 4

[[languages.ko.menus.main]]
name = "커뮤니티"
url = "https://github.com/helm/community"
weight = 5

[languages.ko.params]
language_alternatives = ["en"]

# Portuguese
[languages.pt]
title = "Helm"
description = "Helm - O Gerenciador de Pacotes do Kubernetes."
contentDir = "content/pt"
languageName = "Português"
weight = 8

[[languages.pt.menus.main]]
name = "Início"
url = "/"
weight = 1

[[languages.pt.menus.main]]
name = "Docs"
url = "/docs"
weight = 2

[[languages.pt.menus.main]]
name = "Charts"
url = "https://artifacthub.io/"
weight = 3

[[languages.pt.menus.main]]
name = "Blog"
url = "https://helm.sh/blog"
weight = 4

[[languages.pt.menus.main]]
name = "Communidade"
url = "https://github.com/helm/community"
weight = 5

[languages.pt.params]
language_alternatives = ["en"]

# Russian
[languages.ru]
title = "Helm"
description = "Helm – Менеджер Пакетов Kubernetes."
contentDir = "content/ru"
languageName = "Русский"
weight = 9

[[languages.ru.menus.main]]
name = "Главная"
url = "/"
weight = 1

[[languages.ru.menus.main]]
name = "Документация"
url = "/docs"
weight = 2

[[languages.ru.menus.main]]
name = "Chart-ы"
url = "https://artifacthub.io/"
weight = 3
external = "yes"

[[languages.ru.menus.main]]
name = "Блог"
url = "https://helm.sh/blog"
weight = 4

[[languages.ru.menus.main]]
name = "Сообщество"
url = "https://github.com/helm/community"
weight = 5

[languages.ru.params]
language_alternatives = ["en"]

# Chinese
[languages.zh]
title = "Helm"
description = "Helm - Kubernetes 包管理器"
contentDir = "content/zh"
languageName = "中文"
weight = 10

[[languages.zh.menus.main]]
name = "首页"
url = "/"
weight = 1

[[languages.zh.menus.main]]
name = "文档"
url = "/docs"
weight = 2

[[languages.zh.menus.main]]
name = "应用中心"
url = "https://artifacthub.io/"
weight = 3
external = "yes"

[[languages.zh.menus.main]]
name = "博客"
url = "https://helm.sh/blog"
weight = 4

[[languages.zh.menus.main]]
name = "社区"
url = "https://github.com/helm/community"
weight = 5

[languages.zh.params]
language_alternatives = ["en"]
