baseurl = "https://helm.sh/"
languageCode = "en-us"
title = "Helm"
theme = "helm"

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  title = "Helm"
  description = "Helm - The Kubernetes Package Manager."
  googleAnalyticsId = "UA-42867143-2"
  googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
  jsFiles = [
    "foundation",
    "foundation.accordion",
    "foundation.dropdown",
    "foundation.offcanvas",
    "foundation.slider",
    "foundation.tooltip",
    "modernizr",
    "app"
  ]

[[params.versions]]
version = "v3.0.0"
patch = "stable"
url = "https://helm.sh/docs"
primary = true

[[params.versions]]
version = "v2.16.1"
url = "https://v2.helm.sh/docs"

[[params.versions]]
version = "v2.14.0"
url = "https://v2-14-0.helm.sh/docs"

[Permalinks]
  code = "/:filename/"

[[params.quicklinks]]
title = "Quickstart Guide"
description = "How to install and get started with Helm including instructions for distros, FAQs, and plugins."
url = "/docs/intro/quickstart"

[[params.quicklinks]]
title = "Chart Guide"
description = "Practical steps for building Helm chartsâ€”how to structure, sign, and sync your charts."
url = "/docs/topics/charts"

[[params.quicklinks]]
title = "Video: Intro to Helm"
description = "Watch Matt Farina and Josh Dolitsky present an introduction to Helm at KubeCon 2019."
url = "https://www.youtube.com/watch?v=Zzwq9FmZdsU"

[[params.quicklinks]]
title = "Migrating from v2 to v3"
description = "Read our blog post on how to migrate from Helm v2 to Helm v3."
url = "/blog/migrate-from-helm-v2-to-helm-v3/"

[[params.quicklinks]]
title = "Helm Security Audit"
description = "Helm has been audited and deemed as recommended for public deployment  during a third-party security audit funded by the CNCF."
url = "/blog/2019-11-04-helm-security-audit-results/"