baseurl = "https://v3.helm.sh/"
languageCode = "en-us"
title = "Helm"
theme = "helm"

contentDir = "content"
publishdir = "app"

canonifyURLs = "false"
pluralizeListTitles = "false"
plainIdAnchors = "true"
defaultContentLanguage = "en"
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  title = "Helm"
  author = "Ronan Flynn-Curran"
  description = "Helm - The Kubernetes Package Manager."
  googleAnalyticsId = "UA-42867143-2"
  googleSiteVerification = "dCa3wS47cErhx0IpaxbB85NfcOP-vFxevknVk6fzf5I"
  jsFiles = [
    "foundation",
    "foundation.accordion",
    "foundation.dropdown",
    "foundation.offcanvas",
    "foundation.slider",
    "foundation.tooltip",
    "modernizr",
    "app"
  ]

[Permalinks]
  code = "/:filename/"
