apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helmsh
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: helmsh
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50