apiVersion: v1
kind: Service
metadata:
  name: helmsh
  labels:
    heritage: helmsh
spec:
  ports:
    - name: http
      port: 80
      targetPort: caddy
    - name: https
      port: 443
      targetPort: caddy
  type: LoadBalancer
  selector:
    app: helmsh